Repository fission-suite/cli, pull requests merged in 2019-12, with the labels that each got.

#59 Auto detect urls in fission down
  library/Fission/CLI/Command/Down.hs
  package.yaml
Labels: 👩‍💻👨‍💻 DX, 🤖 CLI

#65 Update cli version number to match package (1.23.0)
  library/Fission/CLI.hs
Labels: 🐛 bug

#60 Change RIO_VERBOSE -> Debug
  app/Main.hs
  stack.yaml
  stack.yaml.lock
Labels: 👩‍💻👨‍💻 DX

#67 fix warnings from compiiler
  app/Main.hs
  library/Fission/CLI/Command/Down.hs
  library/Fission/CLI/Environment.hs
  stack.yaml.lock
Labels: 🐛 bug

#66 Ipfs refactor
  app/Main.hs
  library/Fission/CLI.hs
  library/Fission/CLI/Command/Down.hs
  library/Fission/CLI/Command/Up.hs
  library/Fission/CLI/Command/Watch.hs
  library/Fission/CLI/Config/Base/Types.hs
  library/Fission/CLI/Config/FissionConnected.hs
  library/Fission/CLI/Config/FissionConnected/Types.hs
  library/Fission/CLI/DNS.hs
  library/Fission/CLI/Environment.hs
  library/Fission/CLI/Environment/Partial.hs
  library/Fission/CLI/Environment/Partial/Types.hs
  library/Fission/CLI/Environment/Types.hs
  library/Fission/CLI/IPFS/Connect.hs
  library/Fission/CLI/IPFS/Pin.hs
  library/Fission/Internal/Orphanage/RIO.hs
  library/Fission/Web/Client.hs
  library/Fission/Web/Client/IPFS.hs
  library/Fission/Web/Client/Peers.hs
  package.yaml
  stack.yaml
  stack.yaml.lock
Labels: 💗 enhancement

#68 Update windows pipeline to use copy files
  .azure/azure-windows-template.yml
  stack.yaml
Labels: 🐛 bug, 🚠 infrastructure
