Repository fission-suite/cli, pull requests merged in 2019-11, with the labels that each got.

#12 Add azure pipelines
  azure-pipelines.yml
  test/lint/Main.hs
Labels: 🚠 infrastructure

#13 Multi OS azure config
  .azure/azure-linux-template.yml
  .azure/azure-osx-template.yml
  azure-pipelines.yml
Labels: 🚠 infrastructure

#10 Dynamic Peers in CLI setup
  app/Main.hs
  library/Fission/CLI/Auth.hs
  library/Fission/CLI/Command/Login.hs
  library/Fission/CLI/Command/Logout.hs
  library/Fission/CLI/Command/Register.hs
  library/Fission/CLI/Command/Up.hs
  library/Fission/CLI/Command/Watch.hs
  library/Fission/CLI/Command/Whoami.hs
  library/Fission/CLI/Config/Guard.hs
  library/Fission/CLI/Config/Types.hs
  library/Fission/CLI/Config/Types/BaseConfig.hs
  library/Fission/CLI/Config/Types/LoggedIn.hs
  library/Fission/CLI/DNS.hs
  library/Fission/CLI/Environment.hs
  library/Fission/CLI/Environment/Types.hs
  library/Fission/CLI/IPFS/Connect.hs
  library/Fission/CLI/IPFS/Error/Types.hs
  library/Fission/CLI/IPFS/Pin.hs
  library/Fission/Web/Client/Peers.hs
Labels: 🎛️ config, 🤖 CLI

#27 Azure deploy to github
  .azure/azure-linux-template.yml
  .azure/azure-osx-template.yml
Labels: 💗 enhancement, 🚠 infrastructure

#28 Bump version to 1.21.1
  library/Fission/CLI.hs
  package.yaml
Labels: 🐛 bug

#36 fix some style spelling/styles issues in output
  library/Fission/CLI/Config/Guard.hs
  library/Fission/CLI/IPFS/Connect.hs
Labels: 🐛 bug

#38 Fix multiple compiler warnings, reorder modules
  app/Main.hs
  library/Fission/CLI/Command/Up.hs
  library/Fission/CLI/Command/Watch.hs
  library/Fission/CLI/Config/Base/Types.hs
  library/Fission/CLI/Config/Guard.hs
  library/Fission/CLI/Config/LoggedIn.hs
  library/Fission/CLI/Config/LoggedIn/Error/Types.hs
  library/Fission/CLI/Config/LoggedIn/Types.hs
  library/Fission/CLI/Config/Types.hs
  library/Fission/CLI/Environment.hs
  library/Fission/CLI/IPFS/Connect.hs
  library/Fission/CLI/IPFS/Error/Types.hs
  library/Fission/CLI/IPFS/Pin.hs
  library/Fission/Web/Client/Peers.hs
  package.yaml
Labels: 🐛 bug, 💗 enhancement

#40 Update CLI to version 1.21.3
  library/Fission/CLI.hs
Labels: 🐛 bug, 🤖 CLI

#35 Recursively build hierarchical auth
  library/Fission/CLI/Command/ResetPassword.hs
  library/Fission/CLI/Config/FissionConnected.hs
  library/Fission/CLI/Environment.hs
  library/Fission/CLI/Environment/Error.hs
  library/Fission/CLI/Environment/Partial.hs
  library/Fission/CLI/Environment/Partial/Types.hs
  library/Fission/Web/Client/User.hs
Labels: 👩‍💻👨‍💻 DX, 💗 enhancement

#46 Remove 2 lines committed accidentally
  .azure/azure-linux-template.yml
  .azure/azure-osx-template.yml
Labels: 🐛 bug, 🚠 infrastructure

#49 EXPERIMENT — re-remove PG
  .azure/azure-linux-template.yml
  .azure/azure-osx-template.yml
Labels: 👩‍🔬 experiment

#47 Add ubuntu 18.04 to azure pipeline
  .azure/azure-linux-template.yml
  .azure/azure-osx-template.yml
  azure-pipelines.yml
Labels: 🚠 infrastructure

#54 Add postgres back into build steps
  .azure/azure-linux-template.yml
  .azure/azure-osx-template.yml
  azure-pipelines.yml
Labels: 🚠 infrastructure

#55 Add the ability to set login username and password via cli options
  library/Fission/CLI/Command/Login.hs
  library/Fission/CLI/Command/Login/Types.hs
Labels: 🤖 CLI

#53 Add a project-aware build-dir
  library/Fission/CLI/Command/ResetPassword.hs
  library/Fission/CLI/Command/Up.hs
  library/Fission/CLI/Command/Watch.hs
  library/Fission/CLI/Environment.hs
  library/Fission/CLI/Environment/Partial.hs
  library/Fission/CLI/Environment/Partial/Types.hs
  library/Fission/CLI/Environment/Types.hs
  library/Fission/CLI/Prompt.hs
  library/Fission/CLI/Prompt/BuildDir.hs
Labels: 👩‍💻👨‍💻 DX, 💗 enhancement

#57 Default to checking globalEnv if recursive search finds nothing
  library/Fission/CLI/Environment.hs
  library/Fission/CLI/Environment/Partial.hs
Labels: 🐛 bug

#58 Add local flag for login & register
  library/Fission/CLI/Command/Login.hs
  library/Fission/CLI/Command/Login/Types.hs
  library/Fission/CLI/Command/Register.hs
  library/Fission/CLI/Command/Register/Types.hs
  library/Fission/CLI/Environment.hs
  package.yaml
Labels: 🐇 quick, 👩‍💻👨‍💻 DX, 💗 enhancement
